### ISSUE TITLE
Notification is not working in iOS

### ISSUE THREAD

**Issue by IMDGhanshyam** [anantgarg/ios-objective-c-chat-sdk-demo#5] opened 2018-11-21 07:17 UTC
I had to go through with **https://firebase.google.com/docs/cloud-messaging/ios/client** and there is nothing to change in my code. 

I have sent the notification from Firebase and I was got.
But, Still not get any notification for messages from CometChat.

Please check the below attachments.
![firebase-sentnotification](https://user-images.githubusercontent.com/44672948/48824844-886ecd00-ed8b-11e8-92de-b3da5f4c9104.png)
![testnotification](https://user-images.githubusercontent.com/44672948/48824845-886ecd00-ed8b-11e8-9b1b-5e3d265e235c.png)

_Originally posted by @IMDGhanshyam in https://github.com/CometChat/ios-objective-c-chat-sdk-demo/issue_comments#issuecomment-440561883_

**Comment by anantgarg** [comment] 2018-11-21 07:45
Closing this as duplicate of #3

**Closed as completed by anantgarg** 2018-11-21 07:45 UTC
